/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    hero: Hero;
    theme: Theme;
    typography: Typography;
    seo: Seo;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    typography: TypographySelect<false> | TypographySelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Все исходные картинки сайта. Загружайте в хорошем качестве — от 2000 px по ширине (JPG, PNG, WebP, AVIF или SVG). Обрезка под десктоп и мобилку делается там, где картинку ставят на сайт.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  rotate?: number | null;
  /**
   * Что изображено — для Google и незрячих посетителей. Например: «Шоколадные ПП-батончики FitSweet с орехами».
   */
  alt: {
    ru: string;
    ro: string;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  rotate?: T;
  alt?:
    | T
    | {
        ru?: T;
        ro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Верхняя панель сайта: логотип, меню, переключатель языка, кнопка «Заказать» и корзина.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  style: {
    background: string;
  };
  logo?: {
    show?: boolean | null;
    kind?: ('text' | 'image') | null;
    text?: string | null;
    color?: string | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
    /**
     * SVG или PNG с прозрачным фоном. Высота на сайте — 44 px, ширина подстроится.
     */
    image?: {
      image?: (number | null) | Media;
      variants?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  tagline?: {
    show?: boolean | null;
    text?: {
      ru?: string | null;
      ro?: string | null;
    };
    color?: string | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
  };
  menu?: {
    show?: boolean | null;
    items?:
      | {
          label: {
            ru: string;
            ro: string;
          };
          /**
           * К какому блоку страницы прокрутить при нажатии.
           */
          target: 'catalog' | 'about' | 'where' | 'delivery' | 'box' | 'reviews' | 'instagram' | 'order' | 'url';
          url?: string | null;
          newTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    color?: string | null;
    hoverColor?: string | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
  };
  language?: {
    show?: boolean | null;
    color?: string | null;
  };
  order: {
    show?: boolean | null;
    text?: {
      ru: string;
      ro: string;
    };
    /**
     * К какому блоку страницы прокрутить при нажатии.
     */
    target: 'catalog' | 'about' | 'where' | 'delivery' | 'box' | 'reviews' | 'instagram' | 'order' | 'url';
    url?: string | null;
    newTab?: boolean | null;
    background?: string | null;
    color?: string | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
  };
  cart?: {
    show?: boolean | null;
    color?: string | null;
    badge?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Первый экран: большой заголовок, подзаголовок, кнопки, картинка и строка преимуществ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  section?: {
    show?: boolean | null;
    background?: string | null;
  };
  heading?: {
    /**
     * Каждая строка — с новой строки на сайте и может быть своего цвета.
     */
    lines?:
      | {
          text: {
            ru: string;
            ro: string;
          };
          color?: string | null;
          id?: string | null;
        }[]
      | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
    /**
     * Если строка не помещается в ширину, сайт сам немного уменьшит заголовок.
     */
    size?: ('70' | '85' | '100' | '115' | '130') | null;
  };
  subtitle?: {
    show?: boolean | null;
    text?: {
      ru: string;
      ro: string;
    };
    color?: string | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
  };
  buttons?: {
    items?:
      | {
          text: {
            ru: string;
            ro: string;
          };
          /**
           * К какому блоку страницы прокрутить при нажатии.
           */
          target: 'catalog' | 'about' | 'where' | 'delivery' | 'box' | 'reviews' | 'instagram' | 'order' | 'url';
          url?: string | null;
          newTab?: boolean | null;
          background?: string | null;
          color?: string | null;
          border?: string | null;
          font?: string | null;
          /**
           * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
           */
          weight?: ('300' | '400' | '500' | '600' | '700') | null;
          id?: string | null;
        }[]
      | null;
  };
  media?: {
    show?: boolean | null;
    /**
     * Справа от текста на компьютере, под текстом на телефоне. Это самая заметная картинка сайта.
     */
    picture?: {
      image?: (number | null) | Media;
      crops?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      variants?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    background?: string | null;
    stampShow?: boolean | null;
    stampText?: string | null;
    stampColor?: string | null;
  };
  features?: {
    show?: boolean | null;
    items?:
      | {
          text: {
            ru: string;
            ro: string;
          };
          icon: string;
          /**
           * SVG или PNG с прозрачным фоном, примерно квадратная.
           */
          iconImage?: {
            image?: (number | null) | Media;
            variants?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
          };
          id?: string | null;
        }[]
      | null;
    iconColor?: string | null;
    color?: string | null;
    font?: string | null;
    /**
     * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
     */
    weight?: ('300' | '400' | '500' | '600' | '700') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Фирменные цвета сайта. В настройках разделов цвета выбираются из этого списка.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  colors: {
    cream: string;
    beige: string;
    card: string;
    sage: string;
    white: string;
    green_900: string;
    green_700: string;
    green_500: string;
    green_200: string;
    olive: string;
    choco: string;
    muted: string;
    blush: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Шрифты всего сайта. В настройках разделов у элементов можно выбрать другой шрифт или оставить «Как в оформлении».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "typography".
 */
export interface Typography {
  id: number;
  /**
   * Крупные заголовки разделов: «Десерты, которые хочется есть каждый день», «Наши десерты»…
   */
  heading: string;
  /**
   * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
   */
  headingWeight: '300' | '400' | '500' | '600' | '700';
  /**
   * Меню, кнопки, описания, цены — весь обычный текст.
   */
  body: string;
  /**
   * Логотип текстом и цитаты в отзывах.
   */
  accent: string;
  /**
   * Если у шрифта нет такой насыщенности, браузер возьмёт ближайшую.
   */
  accentWeight: '300' | '400' | '500' | '600' | '700';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Как сайт выглядит в Google и в превью ссылок (Telegram, Facebook, Viber).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Показывается в поиске и на вкладке браузера. Оптимально 50–60 символов.
   */
  title: {
    ru: string;
    ro: string;
  };
  /**
   * Текст под заголовком в поиске. Оптимально 140–160 символов.
   */
  description: {
    ru: string;
    ro: string;
  };
  /**
   * Через запятую. Google их почти не учитывает, но другие поисковики — да.
   */
  keywords?: {
    ru?: string | null;
    ro?: string | null;
  };
  /**
   * Показывается, когда ссылку на сайт отправляют в Telegram, Facebook, Viber. Отдаётся как JPG 1200×630.
   */
  ogImage?: {
    image?: (number | null) | Media;
    crops?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    variants?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  style?:
    | T
    | {
        background?: T;
      };
  logo?:
    | T
    | {
        show?: T;
        kind?: T;
        text?: T;
        color?: T;
        font?: T;
        weight?: T;
        image?:
          | T
          | {
              image?: T;
              variants?: T;
            };
      };
  tagline?:
    | T
    | {
        show?: T;
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
            };
        color?: T;
        font?: T;
        weight?: T;
      };
  menu?:
    | T
    | {
        show?: T;
        items?:
          | T
          | {
              label?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                  };
              target?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        color?: T;
        hoverColor?: T;
        font?: T;
        weight?: T;
      };
  language?:
    | T
    | {
        show?: T;
        color?: T;
      };
  order?:
    | T
    | {
        show?: T;
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
            };
        target?: T;
        url?: T;
        newTab?: T;
        background?: T;
        color?: T;
        font?: T;
        weight?: T;
      };
  cart?:
    | T
    | {
        show?: T;
        color?: T;
        badge?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  section?:
    | T
    | {
        show?: T;
        background?: T;
      };
  heading?:
    | T
    | {
        lines?:
          | T
          | {
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                  };
              color?: T;
              id?: T;
            };
        font?: T;
        weight?: T;
        size?: T;
      };
  subtitle?:
    | T
    | {
        show?: T;
        text?:
          | T
          | {
              ru?: T;
              ro?: T;
            };
        color?: T;
        font?: T;
        weight?: T;
      };
  buttons?:
    | T
    | {
        items?:
          | T
          | {
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                  };
              target?: T;
              url?: T;
              newTab?: T;
              background?: T;
              color?: T;
              border?: T;
              font?: T;
              weight?: T;
              id?: T;
            };
      };
  media?:
    | T
    | {
        show?: T;
        picture?:
          | T
          | {
              image?: T;
              crops?: T;
              variants?: T;
            };
        background?: T;
        stampShow?: T;
        stampText?: T;
        stampColor?: T;
      };
  features?:
    | T
    | {
        show?: T;
        items?:
          | T
          | {
              text?:
                | T
                | {
                    ru?: T;
                    ro?: T;
                  };
              icon?: T;
              iconImage?:
                | T
                | {
                    image?: T;
                    variants?: T;
                  };
              id?: T;
            };
        iconColor?: T;
        color?: T;
        font?: T;
        weight?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        cream?: T;
        beige?: T;
        card?: T;
        sage?: T;
        white?: T;
        green_900?: T;
        green_700?: T;
        green_500?: T;
        green_200?: T;
        olive?: T;
        choco?: T;
        muted?: T;
        blush?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "typography_select".
 */
export interface TypographySelect<T extends boolean = true> {
  heading?: T;
  headingWeight?: T;
  body?: T;
  accent?: T;
  accentWeight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  title?:
    | T
    | {
        ru?: T;
        ro?: T;
      };
  description?:
    | T
    | {
        ru?: T;
        ro?: T;
      };
  keywords?:
    | T
    | {
        ru?: T;
        ro?: T;
      };
  ogImage?:
    | T
    | {
        image?: T;
        crops?: T;
        variants?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}